const COFFEE_ORDERED = 'COFFEE_ORDERED';
const COFFEE_RESTOCKED = 'COFFEE_RESTOCKED';
const COFFEEBEAN_ORDERED = 'COFFEEBEAN_ORDERED';
const COFFEEBEAN_RESTOCKED = 'COFFEEBEAN_RESTOCKED';

module.exports = {
  COFFEE_ORDERED,
  COFFEE_RESTOCKED,
  COFFEEBEAN_ORDERED,
  COFFEEBEAN_RESTOCKED
};