const COFFEE_ORDERED = 'COFFEE_ORDERED';
const COFFEE_RESTOCKED = 'COFFEE_RESTOCKED';
const COFFEEBEAN_ORDERED = 'COFFEEBEAN_ORDERED';
const COFFEEBEAN_RESTOCKED = 'COFFEEBEAN_RESTOCKED';
const CAKE_ORDERED = 'CAKE_ORDERED';
const CAKE_RESTOCKED = 'CAKE_RESTOCKED';
const POKEMON_PENDING = 'POKEMON_PENDING';
const POKEMON_SUCCESSED = 'POKEMON_SUCCESSED';
const POKEMON_FAILED = 'POKEMON_FAILED';

module.exports = {
  COFFEE_ORDERED,
  COFFEE_RESTOCKED,
  COFFEEBEAN_ORDERED,
  COFFEEBEAN_RESTOCKED,
  CAKE_ORDERED,
  CAKE_RESTOCKED,
  POKEMON_PENDING,
  POKEMON_SUCCESSED,
  POKEMON_FAILED
};